### ISSUE TITLE
Add more expensive chunks claims

### ISSUE THREAD

**Issue by ghost** [MarkehMe/SimpleTowns-Economy#1]
Please code a feature to make every single claim more expensive.
Make it as percentage in the config.yml configurable.

For Example:
First Chunk costs 1000$
Second Chunk costs 1010$
Third Chunk 1020,1$
......

In the example is the percent: 1%
So every single Chunk cost 1% more the the chunk before.

The second Chunk is 1% more expensive then the first Chunk.
The third Chunk is 1% more expensive then the second Chunk.

**Comment by ghost** [comment]
[Add]
You can add this feature to Town-Creation too. :)

**Comment by markhughes** [comment]
Thinking of a more 'simple way to do this.. maybe add a configuration option:

Default new configuration option(?):

``` yml
    expenses:
      additionalCostPerChunkOwned: 0
```

So, if we set this to 5, then:

If the player owns 1 chunk, and attempts to purchase a new one - it will now cost +5
If the player owns 3 chunks, and attempts to purchase a new one - it will now cost +15
If the player owns 10 chunks, and attempts to purchase a new one - it will now cost +50

**Comment by ghost** [comment]
Yeah good idea. But add this as percent. It's better.
Mark Hughes notifications@github.com schrieb:

```
  Thinking of a more 'simple way to do this.. maybe add a configuration option:


  Default new configuration option(?):
  expenses:
  additionalPerChunkOwned: 0


  —
  Reply to this email directly or view it on GitHub.
```

**Comment by markhughes** [comment]
Added, will be available in next release. Sorry for the delay.
